# Generated by Django 2.2.2 on 2020-01-30 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0008_profile_past_bookings'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='flights.Flight'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='past_bookings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.Booking'),
        ),
    ]
