# Generated by Django 2.2.2 on 2020-01-30 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0009_auto_20200130_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='tier',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
