# Generated by Django 2.2.2 on 2020-01-30 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0011_booking_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='total',
        ),
    ]
